version: 2

jobs:
  build:
    docker:
      - image: "ubuntu:latest"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'export TZ="America/New_York" && apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Creating Build Files
          command: 'mkdir build && cd build && cmake ..'
      - run:
          name: Build
          command: 'make'
      - run:
          name: Unit Tests
          command: 'cd testing && ./Core6502Tests'