version: 2.1
executors:
  exectr:
    docker:
      - image: evanstoddard/dockercpp:latest
jobs:
  build:
    executor: exectr
    steps:
      - checkout
      - run:
          name: Setup cmake and build artifacts
          command: |
            mkdir build
            cd build
            cmake ..
            make
      - persist_to_workspace:
          root: .
          paths: build
  test:
    executor: exectr
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Execute Tests
          command: |
            cd build/tests
            ./Core6502Tests --gtest_output=XML
      - store_test_results:
          path: build
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build